#!/bin/bash
# Auto-generated by agent — run manually to push and create PRs
# (cleared — tasks 001, 002, 003 already merged into main)

# Task 004: Notifications Page with Unread Badge and Navigation
git push -u origin task/004-notifications-page
gh pr create --base main --head task/004-notifications-page --title "task(004): Notifications Page with Unread Badge and Navigation" --body "Automated migration task. See PLAN/tasks/004-notifications-page.md for details."
gh pr merge --merge --auto

# Task 006: Add Apple Sign-In to Auth Modal
git push -u origin task/006-social-login
gh pr create --base main --head task/006-social-login --title "task(006): Add Apple Sign-In to Auth Modal" --body "Automated migration task. See PLAN/tasks/006-social-login.md for details."
gh pr merge --merge --auto
