#!/bin/bash
# Auto-generated by agent — run manually to push and create PRs
# (cleared — tasks 001, 002, 003 already merged into main)

# Task 004: Notifications Page with Unread Badge and Navigation
git push -u origin task/004-notifications-page
gh pr create --base main --head task/004-notifications-page --title "task(004): Notifications Page with Unread Badge and Navigation" --body "Automated migration task. See PLAN/tasks/004-notifications-page.md for details."
gh pr merge --merge --auto

# Task 006: Add Apple Sign-In to Auth Modal
git push -u origin task/006-social-login
gh pr create --base main --head task/006-social-login --title "task(006): Add Apple Sign-In to Auth Modal" --body "Automated migration task. See PLAN/tasks/006-social-login.md for details."

# Task 016: Implement PostHog Analytics with Full Event Tracking
git push -u origin task/016-posthog-analytics
gh pr create --base main --head task/016-posthog-analytics --title "task(016): Implement PostHog Analytics with Full Event Tracking" --body "Automated migration task. See PLAN/tasks/016-posthog-analytics.md for details."
gh pr merge --merge --auto

# Task 005: Calendar View for User Bookings
git push -u origin task/005-booking-calendar-view
gh pr create --base main --head task/005-booking-calendar-view --title "task(005): Calendar View for User Bookings" --body "Automated migration task. See PLAN/tasks/005-booking-calendar-view.md for details."
gh pr merge --merge --auto

# Task 009: Remove Offers Page
git push -u origin task/009-remove-offers-page
gh pr create --base main --head task/009-remove-offers-page --title "task(009): Remove Offers Page" --body "Automated migration task. See PLAN/tasks/009-remove-offers-page.md for details."
gh pr merge --merge --auto

# Task 012: User-to-Host Mode Switch for Host Profiles
git push -u origin task/012-host-mode-switch
gh pr create --base main --head task/012-host-mode-switch --title "task(012): User-to-Host Mode Switch for Host Profiles" --body "Automated migration task. See PLAN/tasks/012-host-mode-switch.md for details."
gh pr merge --merge --auto
