#!/bin/bash
# Auto-generated by agent — run manually to push and create PRs


# Task 003: Social Feed / Reels with TikTok/Instagram-style Interaction
git push -u origin task/003-social-feed-reels
gh pr create --base main --head task/003-social-feed-reels --title "task(003): Social Feed / Reels with TikTok/Instagram-style Interaction" --body "Automated migration task. See web/PLAN/tasks/003-social-feed-reels.md for details."
gh pr merge --merge --auto
