DELETE FROM room_items;
INSERT INTO room_items (key, category, icon, name) VALUES
('comfort_wi_fi', 'comfort', '📶', '{"en": "Wi-Fi", "fr": "Wi-Fi", "ar": "واي فاي"}'),
('comfort_air_conditioning', 'comfort', '❄️', '{"en": "Air conditioning", "fr": "Climatisation", "ar": "تكييف الهواء"}'),
('comfort_heating', 'comfort', '🔥', '{"en": "Heating", "fr": "Chauffage", "ar": "التدفئة"}'),
('comfort_television', 'comfort', '📺', '{"en": "Television", "fr": "Télévision", "ar": "تلفاز"}'),
('comfort_netflix_smart_tv', 'comfort', '🎬', '{"en": "Netflix / Smart TV", "fr": "Netflix / Smart TV", "ar": "نتفليكس / تلفاز ذكي"}'),
('comfort_private_bathroom', 'comfort', '🚿', '{"en": "Private bathroom", "fr": "Salle de bain privée", "ar": "حمّام خاص"}'),
('comfort_shower', 'comfort', '🚿', '{"en": "Shower", "fr": "Douche", "ar": "دُش"}'),
('comfort_bathtub', 'comfort', '🛁', '{"en": "Bathtub", "fr": "Baignoire", "ar": "حوض استحمام"}'),
('comfort_hot_water', 'comfort', '💧', '{"en": "Hot water", "fr": "Eau chaude", "ar": "ماء ساخن"}'),
('comfort_king_size_bed', 'comfort', '🛏️', '{"en": "King size bed", "fr": "Lit king size", "ar": "سرير كينغ"}'),
('comfort_queen_size_bed', 'comfort', '🛏️', '{"en": "Queen size bed", "fr": "Lit queen size", "ar": "سرير كوين"}'),
('comfort_bed_linens', 'comfort', '🛌', '{"en": "Bed linens", "fr": "Linge de lit", "ar": "أغطية السرير"}'),
('comfort_towels', 'comfort', '🧴', '{"en": "Towels", "fr": "Serviettes", "ar": "مناشف"}'),
('comfort_hair_dryer', 'comfort', '💇‍♀️', '{"en": "Hair dryer", "fr": "Sèche-cheveux", "ar": "مجفف شعر"}'),
('comfort_iron', 'comfort', '👔', '{"en": "Iron", "fr": "Fer à repasser", "ar": "مكواة"}'),
('comfort_wardrobe', 'comfort', '👕', '{"en": "Wardrobe", "fr": "Armoire", "ar": "خزانة ملابس"}'),
('comfort_desk', 'comfort', '💼', '{"en": "Desk", "fr": "Bureau", "ar": "مكتب"}'),
('comfort_living_area', 'comfort', '🛋️', '{"en": "Living area", "fr": "Coin salon", "ar": "منطقة جلوس"}'),
('comfort_fireplace', 'comfort', '🔥', '{"en": "Fireplace", "fr": "Cheminée", "ar": "مدفأة"}'),
('kitchen_equipped_kitchen', 'kitchen', '🍳', '{"en": "Equipped kitchen", "fr": "Cuisine équipée", "ar": "مطبخ مجهز"}'),
('kitchen_kitchenware', 'kitchen', '🍴', '{"en": "Kitchenware", "fr": "Ustensiles de cuisine", "ar": "أواني المطبخ"}'),
('kitchen_oven', 'kitchen', '🔥', '{"en": "Oven", "fr": "Four", "ar": "فرن"}'),
('kitchen_microwave', 'kitchen', '🔌', '{"en": "Microwave", "fr": "Micro-ondes", "ar": "ميكروويف"}'),
('kitchen_refrigerator', 'kitchen', '🧊', '{"en": "Refrigerator", "fr": "Réfrigérateur", "ar": "ثلاجة"}'),
('kitchen_freezer', 'kitchen', '❄️', '{"en": "Freezer", "fr": "Congélateur", "ar": "مجمّد"}'),
('kitchen_coffee_machine', 'kitchen', '☕', '{"en": "Coffee machine", "fr": "Machine à café", "ar": "آلة قهوة"}'),
('kitchen_kettle', 'kitchen', '🍵', '{"en": "Kettle", "fr": "Bouilloire", "ar": "غلاية ماء"}'),
('kitchen_breakfast_included', 'kitchen', '🥐', '{"en": "Breakfast included", "fr": "Petit-déjeuner inclus", "ar": "فطور مشمول"}'),
('kitchen_half_board', 'kitchen', '🍽️', '{"en": "Half board", "fr": "Demi-pension", "ar": "نصف إقامة"}'),
('kitchen_full_board', 'kitchen', '🍲', '{"en": "Full board", "fr": "Pension complète", "ar": "إقامة كاملة"}'),
('kitchen_room_service', 'kitchen', '🛎️', '{"en": "Room service", "fr": "Service de chambre", "ar": "خدمة الغرف"}'),
('parking_free_parking', 'parking', '🅿️', '{"en": "Free parking", "fr": "Parking gratuit", "ar": "موقف مجاني"}'),
('parking_secure_parking', 'parking', '🔒', '{"en": "Secure parking", "fr": "Parking sécurisé", "ar": "موقف مراقب"}'),
('parking_wheelchair_access', 'parking', '♿', '{"en": "Wheelchair access", "fr": "Accès PMR", "ar": "وصول لذوي الاحتياجات الخاصة"}'),
('parking_elevator', 'parking', '🛗', '{"en": "Elevator", "fr": "Ascenseur", "ar": "مصعد"}'),
('outdoor_swimming_pool', 'outdoor', '🏊', '{"en": "Swimming pool", "fr": "Piscine", "ar": "مسبح"}'),
('outdoor_heated_pool', 'outdoor', '🔥🏊', '{"en": "Heated pool", "fr": "Piscine chauffée", "ar": "مسبح مُدفأ"}'),
('outdoor_jacuzzi', 'outdoor', '🛁', '{"en": "Jacuzzi", "fr": "Jacuzzi", "ar": "جاكوزي"}'),
('outdoor_hammam', 'outdoor', '🧖‍♂️', '{"en": "Hammam", "fr": "Hammam", "ar": "حمّام تقليدي"}'),
('outdoor_spa', 'outdoor', '💆', '{"en": "Spa", "fr": "Spa", "ar": "سبا"}'),
('outdoor_gym', 'outdoor', '🏋️', '{"en": "Gym", "fr": "Salle de sport", "ar": "صالة رياضية"}'),
('outdoor_garden', 'outdoor', '🌿', '{"en": "Garden", "fr": "Jardin", "ar": "حديقة"}'),
('outdoor_terrace', 'outdoor', '🌅', '{"en": "Terrace", "fr": "Terrasse", "ar": "تراس"}'),
('outdoor_sea_view', 'outdoor', '🌊', '{"en": "Sea view", "fr": "Vue sur mer", "ar": "إطلالة على البحر"}'),
('outdoor_mountain_view', 'outdoor', '🏔️', '{"en": "Mountain view", "fr": "Vue sur montagne", "ar": "إطلالة على الجبل"}'),
('outdoor_panoramic_view', 'outdoor', '🏞️', '{"en": "Panoramic view", "fr": "Vue panoramique", "ar": "إطلالة بانورامية"}'),
('outdoor_kids_playground', 'outdoor', '👶', '{"en": "Kids playground", "fr": "Aire de jeux", "ar": "ملعب أطفال"}'),
('outdoor_barbecue', 'outdoor', '🔥', '{"en": "Barbecue", "fr": "Barbecue", "ar": "منطقة شواء"}'),
('outdoor_hiking_trails', 'outdoor', '🥾', '{"en": "Hiking trails", "fr": "Randonnées", "ar": "مسارات المشي"}'),
('outdoor_on_site_activities', 'outdoor', '🐎', '{"en": "On-site activities", "fr": "Activités sur place", "ar": "أنشطة في الموقع"}'),
('services_24_7_reception', 'services', '🕒', '{"en": "24/7 reception", "fr": "Réception 24/7", "ar": "استقبال 24/7"}'),
('services_self_check_in', 'services', '🔐', '{"en": "Self check-in", "fr": "Self check-in", "ar": "تسجيل دخول ذاتي"}'),
('services_laundry_service', 'services', '🧺', '{"en": "Laundry service", "fr": "Blanchisserie", "ar": "خدمة غسيل الملابس"}'),
('services_airport_shuttle', 'services', '🚐', '{"en": "Airport shuttle", "fr": "Navette aéroport", "ar": "نقل المطار"}'),
('services_car_rental', 'services', '🚗', '{"en": "Car rental", "fr": "Location de voiture", "ar": "تأجير سيارات"}'),
('services_high_speed_wi_fi', 'services', '🚀', '{"en": "High-speed Wi-Fi", "fr": "Wi-Fi haut débit", "ar": "إنترنت عالي السرعة"}'),
('services_coworking_space', 'services', '💻', '{"en": "Coworking space", "fr": "Espace coworking", "ar": "مساحة عمل مشتركة"}'),
('general_no_pets', 'general', '🚫🐶', '{"en": "No pets", "fr": "Animaux interdits", "ar": "ممنوع الحيوانات"}'),
('general_pets_allowed', 'general', '🐾', '{"en": "Pets allowed", "fr": "Animaux acceptés", "ar": "الحيوانات مسموح بها"}'),
('general_non_smoking', 'general', '🚭', '{"en": "Non-smoking", "fr": "Non-fumeur", "ar": "ممنوع التدخين"}'),
('general_smoking_allowed', 'general', '🚬', '{"en": "Smoking allowed", "fr": "Espace fumeur", "ar": "مسموح التدخين"}'),
('general_quiet_hours_after_10_pm', 'general', '🔇', '{"en": "Quiet hours after 10 PM", "fr": "Silence après 22h", "ar": "الهدوء بعد الساعة 10 مساءً"}'),
('general_no_parties', 'general', '🎉🚫', '{"en": "No parties", "fr": "Fêtes interdites", "ar": "الحفلات ممنوعة"}'),
('general_no_external_visitors', 'general', '🚫🧍', '{"en": "No external visitors", "fr": "Visiteurs externes interdits", "ar": "الزوار الخارجيون ممنوعون"}'),
('general_no_children_allowed', 'general', '🚫👶', '{"en": "No children allowed", "fr": "Enfants non admis", "ar": "الأطفال غير مسموحين"}'),
('general_children_welcome', 'general', '👨‍👩‍👧', '{"en": "Children welcome", "fr": "Enfants bienvenus", "ar": "الأطفال مرحّب بهم"}'),
('general_respect_neighbors', 'general', '🏘️', '{"en": "Respect neighbors", "fr": "Respect du voisinage", "ar": "احترام الجيران"}'),
('documents_marriage_certificate_required', 'documents', '💍', '{"en": "Marriage certificate required", "fr": "Acte de mariage requis", "ar": "عقد الزواج مطلوب"}'),
('documents_id_card_required', 'documents', '🆔', '{"en": "ID card required", "fr": "Carte d’identité requise", "ar": "بطاقة التعريف مطلوبة"}'),
('documents_passport_required', 'documents', '🌍', '{"en": "Passport required", "fr": "Passeport requis", "ar": "جواز السفر مطلوب"}'),
('documents_security_deposit_required', 'documents', '💰', '{"en": "Security deposit required", "fr": "Dépôt de garantie requis", "ar": "وديعة تأمين مطلوبة"}'),
('documents_foreign_tourists_only', 'documents', '✈️', '{"en": "Foreign tourists only", "fr": "Réservé aux touristes étrangers", "ar": "للسياح الأجانب فقط"}'),
('documents_married_couples_only', 'documents', '💑', '{"en": "Married couples only", "fr": "Réservé aux couples mariés", "ar": "للأزواج المتزوجين فقط"}'),
('safety_cameras_in_common_areas', 'safety', '🎥', '{"en": "Cameras in common areas", "fr": "Caméras dans les espaces communs", "ar": "كاميرات في المناطق المشتركة"}'),
('safety_security_guard', 'safety', '🛡️', '{"en": "Security guard", "fr": "Agent de sécurité", "ar": "حارس أمن"}'),
('safety_safe_box', 'safety', '🔒', '{"en": "Safe box", "fr": "Coffre-fort", "ar": "خزنة"}'),
('safety_24_7_surveillance', 'safety', '👁️', '{"en": "24/7 surveillance", "fr": "Surveillance 24/7", "ar": "مراقبة 24/7"}'),
('notes_difficult_road_access', 'notes', '🛣️', '{"en": "Difficult road access", "fr": "Accès difficile", "ar": "طريق صعب / غير معبّد"}'),
('notes_isolated_accommodation', 'notes', '🏞️', '{"en": "Isolated accommodation", "fr": "Logement isolé", "ar": "إقامة منعزلة"}'),
('notes_animals_on_site', 'notes', '🐕', '{"en": "Animals on site", "fr": "Animaux présents sur place", "ar": "وجود حيوانات في الموقع"}'),
('notes_noisy_area', 'notes', '🔊', '{"en": "Noisy area", "fr": "Zone bruyante", "ar": "منطقة مزعجة"}'),
('notes_steep_terrain', 'notes', '⛰️', '{"en": "Steep terrain", "fr": "Terrain escarpé", "ar": "تضاريس منحدرة"}'),
('notes_possible_allergens', 'notes', '🌾', '{"en": "Possible allergens", "fr": "Risque d’allergènes", "ar": "احتمال وجود مسببات حساسية"}'),
('payment_payment_on_arrival', 'payment', '💵', '{"en": "Payment on arrival", "fr": "Paiement à l''arrivée", "ar": "الدفع عند الوصول"}'),
('payment_online_payment_mandatory', 'payment', '💳', '{"en": "Online payment mandatory", "fr": "Paiement en ligne requis", "ar": "الدفع الإلكتروني إلزامي"}'),
('payment_minimum_stay_2_nights', 'payment', '📅', '{"en": "Minimum stay (2 nights)", "fr": "Séjour minimum (2 nuits)", "ar": "الحد الأدنى للإقامة (ليلتان)"}'),
('payment_flexible_check_in', 'payment', '⏱️', '{"en": "Flexible check-in", "fr": "Check-in flexible", "ar": "تسجيل دخول مرن"}'),
('payment_flexible_check_out', 'payment', '⏳', '{"en": "Flexible check-out", "fr": "Check-out flexible", "ar": "تسجيل خروج مرن"}'),
('payment_tourist_tax_not_included', 'payment', '🧾', '{"en": "Tourist tax not included", "fr": "Taxe de séjour non incluse", "ar": "الضريبة السياحية غير مشمولة"}')
;
